### ISSUE TITLE
Mirror on F.Cu and B.Cu?

### ISSUE THREAD

**Issue by theopensourcerer** [mtl/svg2mod#12]
I think I must be being a bit thick but I am trying to get the attached SVG to footprint where the pattern is on both the front and back copper layers. When I run the command

` ~/bin/svg2mod/svg2mod.py -i cap.svg --format=pretty`

I get a kicad_mod file but the copper pattern is only ever on F.Cu. And I'm sorry but I don't really understand the bit in your README.md:

> Drawing elements will be mapped to front layers by default. Mirrored images of these elements can be automatically generated and mapped to back layers in a separate module (see --front-only option).

Is there a way I can get this pattern on both sides of the footprint?

TIA

[cap.svg.zip](https://github.com/mtl/svg2mod/files/818723/cap.svg.zip)

**Comment by kasbah** [comment]
I am not sure but I think you might have to split this into two SVGs or amend the script.

**Comment by theopensourcerer** [comment]
Just FYI - I simply copied all the data from the mod file which was on F.Cu and did a search and replace to replace F.Cu with B.Cu, then pasted this back into the mod file. Seems to work correctly.

**Comment by kasbah** [comment]
Ah, that's smarter, yes. Still we should probably amend the script to specify exact layers.
