### ISSUE TITLE
No Module Named SVG

### ISSUE THREAD

**Issue by bmmcwhirt** [mtl/svg2mod#13]
$ ./svg2mod.py -i keyboard-layout-outline.svg -o keyboard.mod 
Traceback (most recent call last):
  File "./svg2mod.py", line 10, in <module>
    import svg
ImportError: No module named svg

**Comment by kasbah** [comment]
What was the solution?

**Comment by bmmcwhirt** [comment]
git did not fully pull the svg directory. Also on a mac at least you have to run the script from inside it's directory using relative paths unless you install the included svg lib.
