### ISSUE TITLE
Why this simple SVF doesn't convert

### ISSUE THREAD

**Issue by emard** [mtl/svg2mod#25]
This is a short svg logo I'd like to convert:

https://hr.wikipedia.org/wiki/Datoteka:Kon%C4%8Dar_Logo.svg

svg2mod creates a kicad mod file but in this file thera are no
drawing objects (file appears as empty).

Can you help to convert it?

**Comment by kasbah** [comment]
Hello! You have to put it on a layer named `SilkS` or `Cu` or something else depending what layer you want. Here you go: https://cloud.monostable.co.uk/kon.kicad_mod

For simple logos like this it might be easier to use the PNG and use KiCad's built in bitmap2component tool. For more complicated graphics with multiple layers, to avoid having to make sure everything is a full separated enclosed path, I would recommend Inkscape with [svg2shenzhen](https://github.com/badgeek/svg2shenzhen).

**Comment by emard** [comment]
Thanx, with proper layer name svg2mod works wonderful!

**Comment by kasbah** [comment]
NP, seems like you can close this issue.

**Comment by emard** [comment]
Absolutely (actually wasn't issue at all)
