### ISSUE TITLE
Maintainer Inactive

### ISSUE THREAD

**Issue by herostrat** [mtl/svg2mod#37]
Hey guys and @mtl,

there are a lot of sensible and good PRs ready to be merged.
This project is interesting and useful for KiCad.

Is there a plan for future development or is this project abandoned?
If so, is anybody interested in continuing work on it?

Best

**Comment by terje** [comment]
Hi @herostrat!

I'm absolutely interested in the continued development and fixing of this useful tool. I've forked it here and incorporated the pull requests from this repo: https://github.com/terje/svg2mod

I don't mind where it lives, so if anyone has a special interest in hosting this under their name I'm game. cc @markrages, @zirafa, @marcan, @n1zzo, @matthijskooijman, @NaH012.

For starters, we could transfer the relevant open issues and get to work. :)

All this assuming @mtl is not interested in managing this project.

**Comment by Sodium-Hydrogen** [comment]
Hey @terje I would be interested in having this on my @Sodium-Hydrogen account. I initially made my changes under my alt account @NaH012, but have since moved everything to this account.

Repo: [https://github.com/Sodium-Hydrogen/svg2mod/](https://github.com/Sodium-Hydrogen/svg2mod/)

**Comment by matthijskooijman** [comment]
I'm not interested in maintaining this (or rather, I won't have time to maintain this). Great that you are looking into this, though :-)

**Comment by Sodium-Hydrogen** [comment]
If no one else has a problem with me taking over maintenance of this project I will go a head with informing all open issues of this and posting on the wiki page for this repo.

**Comment by matthijskooijman** [comment]
I just have one suggestion: Maybe it would be interesting to create an organization for this repo, or maybe see if it can be put under the KiCad organization? Having an organization makes it easier to distribute or transfer maintainership in the future, and also makes the repo look a bit more official? Just an idea though, just putting it under a personal account is *probably* more pragmatic.

**Comment by Sodium-Hydrogen** [comment]
I do like your idea for using an organization. I just created the [svg2mod](https://github.com/svg2mod) org. If you or anyone else who has been reading this thread would like to join to make sure this project doesn't die again send me a message.

I decided to not try getting it added to the kicad organization because some of the more recent nightly builds have a very limited version integrated so I don't see the interest being very high.

[Repo: https://github.com/svg2mod/svg2mod](https://github.com/svg2mod/svg2mod)

**Comment by zirafa** [comment]
It'd be great to hear from @mtl first, but an org sounds like a decent idea and would help consolidate the various forks/patches. I'd be interested in helping maintain the project as much as I can

**Comment by javl** [comment]
@Sodium-Hydrogen Any special reason for not having an issue tracker active on your new svg2mod repo?

**Comment by Sodium-Hydrogen** [comment]
No I thought it was active when I set it up. It should be good to go now. Thanks
